"""initial schema

Revision ID: 911953bd9aa0
Revises: 
Create Date: 2026-05-14 19:25:51.383768

"""
from alembic import op
import sqlalchemy as sa


revision = '911953bd9aa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_news_articles_processed', 'news_articles', ['processed'], unique=False)
    op.create_index('ix_news_articles_published', 'news_articles', ['published_at'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_class', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_bars_symbol_fetched', 'price_bars', ['symbol', 'fetched_at'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('time_horizon', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('event_ids', sa.JSON(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trading_signals_asset', 'trading_signals', ['asset'], unique=False)
    op.create_index('ix_trading_signals_generated_at', 'trading_signals', ['generated_at'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_article_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('affected_assets', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('llm_enriched', sa.String(length=5), nullable=False),
    sa.Column('extraction_method', sa.String(length=10), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_events_category', 'market_events', ['category'], unique=False)
    op.create_index('ix_market_events_extracted_at', 'market_events', ['extracted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_events_extracted_at', table_name='market_events')
    op.drop_index('ix_market_events_category', table_name='market_events')
    op.drop_table('market_events')
    op.drop_index('ix_trading_signals_generated_at', table_name='trading_signals')
    op.drop_index('ix_trading_signals_asset', table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index('ix_price_bars_symbol_fetched', table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index('ix_news_articles_published', table_name='news_articles')
    op.drop_index('ix_news_articles_processed', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
