"""add regime columns to paper trades

Revision ID: eb499ac8a4b5
Revises: 911953bd9aa0
Create Date: 2026-05-16 10:02:12.837744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'eb499ac8a4b5'
down_revision = '911953bd9aa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_outcomes_asset', table_name='signal_outcomes')
    op.drop_index('ix_signal_outcomes_status', table_name='signal_outcomes')
    op.drop_table('signal_outcomes')
    op.add_column('paper_trades', sa.Column('regime_at_open', sa.String(length=50), nullable=True))
    op.add_column('paper_trades', sa.Column('regime_at_close', sa.String(length=50), nullable=True))
    op.add_column('paper_trades', sa.Column('audit_entry', sa.JSON(), nullable=True))
    op.add_column('paper_trades', sa.Column('audit_exit', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_trades', 'audit_exit')
    op.drop_column('paper_trades', 'audit_entry')
    op.drop_column('paper_trades', 'regime_at_close')
    op.drop_column('paper_trades', 'regime_at_open')
    op.create_table('signal_outcomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('time_horizon', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('price_at_signal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('take_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_at_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_change_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('market_regime', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('event_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='signal_outcomes_pkey'),
    sa.UniqueConstraint('signal_id', name='uq_signal_outcomes_signal_id')
    )
    op.create_index('ix_signal_outcomes_status', 'signal_outcomes', ['status'], unique=False)
    op.create_index('ix_signal_outcomes_asset', 'signal_outcomes', ['asset'], unique=False)
    # ### end Alembic commands ###
